spring.application.name=monitor-api

spring.datasource.url=jdbc:postgresql://localhost:5432/network_monitor
spring.datasource.username=nm_app
spring.datasource.password=nm_app

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true